name: zxbase_model
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://zxbase.com
publish_to: none

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  cryptography: ^2.0.0
  uuid: ^3.0.0
  zxbase_crypto:
    git: https://github.com/zxbase/zxbase_crypto

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
